const ADD_TODO = 'ADD_TODO';
const SHOW_TODO = 'SHOW_TODO';
const DELETE_TODO = 'DELETE_TODO';
const ADD_COMMENT = 'ADD_COMMENT';
const COMMENT = 'COMMENT';
const FLAG = 'FLAG';

export {ADD_TODO, SHOW_TODO, DELETE_TODO, ADD_COMMENT, COMMENT, FLAG};